version: "3.9"

services:
  bun:
    build: .
    image: baderidris/littlebun
    environment:
      - PORT=3000
    depends_on:
      - mongo
  nginx:
    image: nginx:stable-alpine
    ports:
      - "5000:80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./views:/usr/share/nginx/html/views
      - ./public:/usr/share/nginx/html/public
  mongo:
    image: mongo:4.4
    # try installing new versions, on prod servers! needs newer CPUs than mine
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Bader
      - MONGO_INITDB_ROOT_PASSWORD=myPassword
    volumes:
      - mongo-db:/data/db
      - ./config/mongo/mongod.conf:/etc/mongod.conf  # Mount the custom configuration file
    command: mongod --config /etc/mongod.conf  # Specify the custom configuration file path
  redis:
    image: redis
    # volumes:
    #   - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      # - ./server/redis/.overcommit_memory:/proc/sys/vm/overcommit_memory
    # command:
      # - sh -c "echo 1 > /proc/sys/vm/overcommit_memory"
      # - ./redis-server /usr/local/etc/redis/redis.conf
      # - redis-server AUTH default myPassword
      # - AUTH default myPassword
  # node:
    # image: node:lts
    # command:
      # - npm install
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: articles
    volumes:
      - ./config/psql/postgresql.conf:/etc/postgresql/postgresql.conf
  adminer:  # i think it's not important to have
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  mongo-db: