version: "3.9"
services:
  nginx:
    ports:
      - "3000:80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
  bun:
    build:
      context: .
      args:
        BUN_ENV: development
    volumes:
      # - ./:/app
      # - /app/bun.lockb
      - ./config/nodemon.json:/app/nodemon.json
    environment:
      - BUN_ENV=development
      - MONGO_USER=Bader
      - MONGO_PASSWORD=myPassword
      - SESSION_SECRET=someSecret
      - REDIS_USER=Bader
      - REDIS_PASSWORD=myPassword
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=articles
    command: sh -c 'bun install && bun --watch run start'
    # command: sh -c 'bun --force pm migrate && bun --watch run start'  🔴 or run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Bader
      - MONGO_INITDB_ROOT_PASSWORD=myPassword